### ISSUE TITLE
Publish Package Error

### ISSUE THREAD

**Issue by condorheroblog** [xunmi1/light-print#4]
I noticed that publishing using the prevention mode encountered the following error: https://github.com/xunmi1/light-print/actions/runs/5503865073/jobs/10029484216

```bash
npm publish --provenance
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-07-10T03_57_11_460Z-debug-0.log
Error: Process completed with exit code 1.
```

I found a solution here: https://github.com/renovatebot/renovate/pull/21612

**Comment by xunmi1** [comment]
v2.0.6 has been released.
